<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaTrimmedPreviewerPackageVersion>11.3.0</AvaloniaTrimmedPreviewerPackageVersion>
    <AvaloniaPreviewerNetCoreToolPath>dotnet</AvaloniaPreviewerNetCoreToolPath>
  </PropertyGroup>

  <!-- Import Avalonia Design-time targets -->
  <ItemGroup>
    <CompilerVisibleProperty Include="AvaloniaPreviewerNetCoreToolPath" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="AnimatedImage.Avalonia" Version="2.0.0" />
    <PackageReference Include="Avalonia" Version="11.3.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.0" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.0" />
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.2.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.6" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.0">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="ReactiveUI" Version="20.2.45" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Fonts\**" />
    <AvaloniaResource Include="Image\**" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <!-- Копіюємо файли локалізації та інші важливі директорії -->
  <ItemGroup>
    <ContentWithTargetPath Include="Assets\Localization\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Assets\Localization\%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
    
    <ContentWithTargetPath Include="Assets\DataBase\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Assets\DataBase\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
    
    <ContentWithTargetPath Include="Assets\Images\Avatar\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Assets\Images\Avatar\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>

    <!-- Копіюємо всі файли з директорії Assets у вихідну директорію -->
    <ContentWithTargetPath Include="Assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
  
  <!-- Import design time targets for Avalonia previewer -->
  <Import Project="$(AvaloniaPreviewerNetCoreAppPath)\IncludeAvaloniaPreviewerProps" Condition="'$(IncludeAvaloniaPreviewerProps)' != 'true' AND '$(AvaloniaPreviewerNetCoreAppPath)' != ''" />
</Project>
